default_language_version:
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.21.0
    hooks:
      - id: yamllint
  # Docker
  - repo: https://github.com/CoRfr/dockerfile-pre-commit
    # Use the revision rev you want to point at
    rev: "fd7dca7bc1b4739848e05011899037157b3862e4"
    hooks:
      - id: dockerlint
        args:
          - --ignore=DL3003
          - --ignore=DL3008
          - --ignore=DL4005
  # Python
  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.7
    hooks:
      - id: flake8
        args:
          - --ignore=E203,E501,W503
  - repo: https://github.com/prettier/prettier
    # Use the sha or tag you want to point at
    rev: "2.0.5"
    hooks:
      - id: prettier
